# current position of robot
float64 current_x
float64 current_y
float64 current_yaw
float64 current_goal_x
float64 current_goal_y

---

# obstacle avoidance service Response
float64 streering_direction