# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtlebot3_autorace_msgs/MovingParam.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MovingParam(genpy.Message):
  _md5sum = "603d953881321b4196ac96fba411105f"
  _type = "turtlebot3_autorace_msgs/MovingParam"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """########################################
# CONSTANTS
########################################
uint8 MOVING_TYPE_IDLE = 0
uint8 MOVING_TYPE_LEFT = 1
uint8 MOVING_TYPE_RIGHT = 2
uint8 MOVING_TYPE_FORWARD = 3
uint8 MOVING_TYPE_BACKWARD = 4

########################################
# Messages
########################################
uint8 moving_type
float32 moving_value_angular
float32 moving_value_linear"""
  # Pseudo-constants
  MOVING_TYPE_IDLE = 0
  MOVING_TYPE_LEFT = 1
  MOVING_TYPE_RIGHT = 2
  MOVING_TYPE_FORWARD = 3
  MOVING_TYPE_BACKWARD = 4

  __slots__ = ['moving_type','moving_value_angular','moving_value_linear']
  _slot_types = ['uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       moving_type,moving_value_angular,moving_value_linear

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MovingParam, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.moving_type is None:
        self.moving_type = 0
      if self.moving_value_angular is None:
        self.moving_value_angular = 0.
      if self.moving_value_linear is None:
        self.moving_value_linear = 0.
    else:
      self.moving_type = 0
      self.moving_value_angular = 0.
      self.moving_value_linear = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2f().pack(_x.moving_type, _x.moving_value_angular, _x.moving_value_linear))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.moving_type, _x.moving_value_angular, _x.moving_value_linear,) = _get_struct_B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2f().pack(_x.moving_type, _x.moving_value_angular, _x.moving_value_linear))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.moving_type, _x.moving_value_angular, _x.moving_value_linear,) = _get_struct_B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2f = None
def _get_struct_B2f():
    global _struct_B2f
    if _struct_B2f is None:
        _struct_B2f = struct.Struct("<B2f")
    return _struct_B2f
